version: '3.8'
services:
  dev-db:
    image: postgres:13
    container_name: bank-account
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nest
    networks:
      - testprojects
networks:
  testprojects:
